Repository LNP-BP/docker, pull requests merged in 2020-09, with the labels that each got.

#9 Add rgb-node docker image
  rgb-node/Dockerfile
Labels: enhancement

#21 Refactoring Dockerfiles with arguments
  Dockerfile/bitcoind-signet/Dockerfile
  Dockerfile/bitcoind/Dockerfile
  Dockerfile/bitcoind/with-wallet/Dockerfile
  Dockerfile/electrs-signet/Dockerfile
  Dockerfile/electrs/Dockerfile
  Dockerfile/elementsd/Dockerfile
  Dockerfile/elementsd/bin/entrypoint
  Dockerfile/elementsd/with-wallet/Dockerfile
  Dockerfile/lightningd-signet/Dockerfile
  Dockerfile/lightningd-signet/bin/lcli
  Dockerfile/lightningd/Dockerfile
  Dockerfile/lightningd/bin/lcli
  README.md
  bitcoin.conf
  docker-compose/.env
  docker-compose/mainnet/docker-compose.yml
  docker-compose/signet/docker-compose.yml
  docker-compose/testnet/docker-compose.yml
Labels: documentation, enhancement

#22 testnet-compose lightningd fix
  docker-compose/testnet/docker-compose.yml
Labels: bug
